# ======================== GERAIS
telegram_token = "6357672250:AAFfn3fIDi-3DS3a4DuuD09Lf-ERyoMgGSY"
gmail_app_password = "anoe gegm boqj ldzo"
email_sender = "avisoscanal1milhao@gmail.com"

# ======================== CURTO PRAZO
telegram_chat_id_curto = "-1002046197953"
email_recipient_curto = "listasemanal@googlegroups.com"
supabase_url_curto = "https://kflwifvrkcqmrzgpvhqe.supabase.co"
supabase_key_curto = "eyJh...BjiP1y8"

# ======================== CURTISSIMO PRAZO
telegram_chat_id_curtissimo = "-1002074291817"
email_recipient_curtissimo = "listacurtissimo@googlegroups.com"
supabase_url_curtissimo = "https://kflwifvrkcqmrzgpvhqe.supabase.co"
supabase_key_curtissimo = "eyJh...BjiP1y8"

# ======================== CLUBE
telegram_chat_id_clube = "-1002533284493"
supabase_url_clube = "https://kflwifvrkcqmrzgpvhqe.supabase.co"
supabase_key_clube = "eyJh...BjiP1y8"

# ======================== LOSS CURTO
telegram_chat_id_losscurto = "-1002046197953"
email_recipient_losscurto = "listasemanal@googlegroups.com"
supabase_url_losscurto = "https://kflwifvrkcqmrzgpvhqe.supabase.co"
supabase_key_losscurto = "eyJh...BjiP1y8"

# ======================== LOSS CURTISSIMO
telegram_chat_id_losscurtissimo = "-1002074291817"
email_recipient_losscurtissimo = "listacurtissimo@googlegroups.com"
supabase_url_losscurtissimo = "https://kflwifvrkcqmrzgpvhqe.supabase.co"
supabase_key_losscurtissimo = "eyJh...BjiP1y8"

# ======================== LOSS CLUBE
telegram_chat_id_lossclube = "-1002533284493"
supabase_url_lossclube = "https://kflwifvrkcqmrzgpvhqe.supabase.co"
supabase_key_lossclube = "eyJh...BjiP1y8"
